---
title: " lecture0919 template"
author: "Yaduo Wang"
date: "2023-09-19"
output: github_document
---

```{r, message = FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

Let's import the `FAS_litters.csv` using a relative path.
```{r}
litters_df=
  read_csv("FAS_litters.csv")
litters_df
```

```{r}
litters_df = janitor::clean_names(litters_df)
```

import the same dataset using an absolute path.
```{r}
litters_df_abs=
  read_csv("/Users/wangyaduo/Downloads/P8105 Data Science/Lecture/data_wrangling-I/FAS_litters.csv")
litters_df_abs
litters_df_abs = janitor::clean_names(litters_df_abs)
```

Exercise 1
```{r}
pups_df=
  read_csv("FAS_pups.csv")
pups_df
pups_df = janitor::clean_names(pups_df)
```

```{r}
pups_df_abs=
  read_csv("/Users/wangyaduo/Downloads/P8105 Data Science/Lecture/data_wrangling-I/FAS_pups.csv")
pups_df_abs
pups_df_abs = janitor::clean_names(pups_df_abs)

```

##Look at data
```{r}
litters_df
head(litters_df)
tail(litters_df)
```

You can use view.
```{r, eval=FALSE}
view(litters_df)
```

```{r}
str(litters_df)
skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df=
  read_csv("FAS_litters.csv", 
           skip = 10, 
           col_names = FALSE, 
           na = c("NA", 19))
```

column types 
```{r}
litters_df=
  read_csv("FAS_litters.csv", 
           col_types = 
             cols(
               'GD0 weight' = col_factor()
             ))
```

##Other File type
import a xlsx file first.
```{r}
mlb_df = 
  read_excel("mlb11.xlsx")
```

Import a SAS file
```{r}
pulse_df = 
  read_sas("public_pulse_data.sas7bdat")
```

##Base R

```{r, eval = FALSE}
litters_df = 
  read.csv("FAS_litters.csv")
litters_df$Gr
```

##Export data 
We have code that "cleans"
```{r}
litters_df_cleaned=
  read_csv("FAS_litters.csv")

litters_df_cleaned = janitor::clean_names(litters_df_cleaned)
write_csv(litters_df_cleaned, "FAS_litters_cleaned.csv")
```

